#!/bin/ksh
date
export PS4='$SECONDS + '
set -x

#############################################################
# NOTE: This job depends on the prod_util module being loaded
#############################################################

#####################################################################################
# Run config file to get input parameters
# NOTE: $gldas_ver must be exported by the submission script prior to running this job (in run_all of lsf directory)!
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd
# DEV_ECF: If the job is to be running using SMS, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
# SENDECF: Flag Events on ecFlow
# SENDCOM: Copy Files From $TMPDIR to $COMOUT
# SENDDBN: Issue DBNet Client Calls
#
# History:  2019 10 15 Jesse Meng and Youlong Xia, first version
#####################################################################################
if [ "$RUN_ENVIR" != "nco" ]      ### For Developers
then
  export gldas_ver=${gldas_ver:-v2.3.0}
#  export HOMEgldas=${HOMEgldas:-/gpfs/dell2/emc/modeling/noscrub/$LOGNAME/gldas.${gldas_ver}}
  export HOMEgldas=${HOMEgldas:-/gpfs/dell2/emc/retros/noscrub/Youlong.Xia/GLDAS}
  export PARA_CONFIG=${gldas_para_config:-$HOMEgldas/user/gldas_para_config}
  if [ -s $PARA_CONFIG ] ; then . $PARA_CONFIG ; fi
  export DATA=${DATA:-/gpfs/dell2/ptmp/$LOGNAME/tmpnwprd}
  export SENDECF=${SENDECF:-NO}
  export SENDDBN=${SENDDBN:-NO}
  export SENDCOM=${SENDCOM:-YES}
  export jobid="LL${job}_${envir}.o$$"
  export jlogfile=${jlogfile:-$DATA/jlogfiles/jlogfile.${jobid}}
fi

########################################################
# obtain unique process id and make temp directory
########################################################
mkdir -p $DATA
cd $DATA

export cyc=${cyc:-00}
export cycle=t${cyc}z

##########################
# Specify NET and RUN Name
##########################
export NET=${NET:-gldas}
export RUN=${RUN:-gldas}

export model=${model:-noah}
export MODEL=${MODEL:-`echo $model |tr '[a-z]' '[A-Z]'`}

###########################
# Define alert_type
###########################
if [ "$RUN_ENVIR" = "prod" -a "$envir" != "prod" ]; then
  export alert_type=GLDAS_GB2_PARA
fi

export alert_type=${alert_type:-GLDAS_GB2}

export pgmout="OUTPUT.$$"

####################################
# Specify Execution Areas
####################################
export FIXgldas=${FIXgldas:-$HOMEgldas/fix}
export PARMgldas=${PARMgldas:-$HOMEgldas/parm}
export EXECgldas=${EXECgldas:-$HOMEgldas/exec}
export USHgldas=${USHgldas:-$HOMEgldas/ush}

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. ./PDY

export GDATE=${GDATE:-$PDY}
echo "GLDAS CYCLE = ${GDATE}.${cycle}"

##############################################
# Define COM directories
##############################################
if [ "$RUN_ENVIR" = "nco" ] ### For nco operation
then

export gldas_ver=${gldas_ver:-v2.3.0}
export HOMEgldas=${HOMEgldas:-/gpfs/dell1/nco/ops/nwprod/gldas.${gldas_ver}}
export PARA_CONFIG=${gldas_para_config:-$HOMEgldas/user/gldas_para_config}
if [ -s $PARA_CONFIG ] ; then . $PARA_CONFIG ; fi

export COM_IN=${COM_IN:-${COMROOT:?}/${NET}/${envir}}
export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}

export COMIN=$COM_IN/gldas.${PDY}
export COMOUT=$COM_OUT/gldas.${PDY}
export COMOUTp1=$COM_OUT/gldas.${PDYp1}

export LOGDIR=${LOGDIR:-${COMROOT}/${NET}/${envir}/logdir}

mkdir -m 775 -p $COMOUT $COMOUTp1 $LOGDIR

env
fi
#############################################################
# execute the script
echo "----------${FCSTSH:-$HOMEgldas/scripts/exgdas_gldas.sh.ecf}----------"
$HOMEgldas/scripts/exgdas_gldas.sh.ecf

cat $pgmout

msg="JGDAS_GLDAS ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
###if [ "$KEEPDATA" != "YES" ]; then rm -rf $DATA; fi

date
